### ISSUE TITLE
A problem with a newline when writing FASTQ

### ISSUE THREAD

**Issue by HatakeKakaxi** [cartoonist/kseqpp#9]
When writing a FASTQ file using this library, I find a newline is added into sequence line and quality line by default. My output result is like this:
```
@name
AGAAAGCTTCATGTTTCAATTGGCCAAAGAATAAGGTAGAGTACGGTAGAAAATAGAGTG
AGCGAACAAA
+
222222222222222222222222222222222222222222222222222222222222
2222222222
```
Is there any way to avoid the newline?

**Comment by cartoonist** [comment]
When output format is not specified the writer wrapped the sequence (and qual) for both FASTA and FASTQ records. If you want to write into a FASTQ file without line wrapping, you should pass `klib::format::fastq` as the last argument when instantiating a `SeqStream` object. Take a look at [this section](https://github.com/cartoonist/kseqpp#wrapping-seqqual-lines) of the README for more details. Here is an example:

```c++
using namespace klib;

SeqStreamOut oss("output.fq", format::fastq);
for (auto&& r : records) oss << r;  // should write records without wrapping

SeqStreamOut oss_gz("output.fq.gz", /* gzip compression */ true, format::fastq);
for (auto&& r : records) oss_gz << r;
```

**Comment by HatakeKakaxi** [comment]
I got it. Thank you.
